version: '3.8'
services:
  mongodocker:
    image: mongo:latest
    container_name: mongodocker
    restart: unless-stopped
    ports:
      - "27017:27017"



#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password

#    volumes:
#      - ./database-data:/data/db


  # Mongo Express Service
#  mongo-express:
#    image: mongo-express:latest # latest image
#    container_name: mongo-express
#    restart: unless-stopped
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_SERVER: mongodb

  # Spring-Reactive-App container

  spring-reactive-app:
    image: spring-reactive-app:1.0
    container_name: spring-reactive-app
    ports:
      - "8080:8080"
    links:
      - mongodocker
