spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive_data
#      username: root
#      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"


